import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const openSans = Open_Sans({ subsets: ["cyrillic", "latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={clsx(
					openSans,
					"bg-gradient-to-br from-white to-slate-600 min-h-screen"
				)}>
				<div className='w-[1512px] m-auto'>{children}</div>
			</body>
		</html>
	);
}
